import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import type { AnalysisGraphData } from "@/types/graph";

function generateMarkdown(analysis: any): string {
  const graphData = analysis.graphData as AnalysisGraphData;
  const security = (analysis.securityScan as any[]) ?? [];

  const lines: string[] = [
    `# ${analysis.name} — Architecture Documentation`,
    `\n*Generated by PRAXIS on ${new Date(analysis.createdAt).toLocaleDateString()}*\n`,
    `## Overview\n`,
    graphData.aiSummary ?? "No summary available.",
    `\n## Components\n`,
  ];

  Object.values(graphData.details).forEach((node) => {
    lines.push(`### ${node.name} (\`${node.type}\`)`);
    lines.push(`\n**Risk Score:** ${node.riskScore}/100\n`);
    lines.push(`${node.description}\n`);
    lines.push(`**Metrics:**`);
    lines.push(`- Lines of Code: ${node.metrics.loc}`);
    lines.push(`- Imports: ${node.metrics.imports}`);
    lines.push(`- Complexity: ${node.metrics.complexity}\n`);
    if (node.dependencies.length > 0) {
      lines.push(`**Dependencies:** ${node.dependencies.join(", ")}\n`);
    }
    if (node.remediations?.length) {
      lines.push(`**AI Recommendations:**`);
      node.remediations.forEach((r) => lines.push(`- ${r}`));
      lines.push("");
    }
  });

  if (security.length > 0) {
    lines.push(`## Security Findings\n`);
    const bySeverity: Record<string, typeof security> = { critical: [], high: [], medium: [], low: [] };
    security.forEach((f) => bySeverity[f.severity]?.push(f));

    ["critical", "high", "medium", "low"].forEach((sev) => {
      if (bySeverity[sev].length === 0) return;
      lines.push(`### ${sev.charAt(0).toUpperCase() + sev.slice(1)}\n`);
      bySeverity[sev].forEach((f) => {
        lines.push(`**[${f.type}]** \`${f.file}\`${f.line ? `:${f.line}` : ""}`);
        lines.push(`${f.description}`);
        lines.push(`> ${f.recommendation}\n`);
      });
    });
  }

  return lines.join("\n");
}

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const analysis = await prisma.analysis.findFirst({
    where: { id: params.id, userId: session.user.id },
  });

  if (!analysis) {
    return NextResponse.json({ error: "Analysis not found" }, { status: 404 });
  }

  const markdown = generateMarkdown(analysis);

  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${analysis.name.replace(/[^a-z0-9]/gi, "-")}-architecture.md"`,
    },
  });
}
