import PptxGenJS from "pptxgenjs";
import type { AnalysisGraphData, GraphNodeDetails } from "@/types/graph";

const THEME = {
  bg: "0B0F14",
  panel: "101722",
  accent: "5B8CFF",
  accentViolet: "8B5CF6",
  text: "E2E8F0",
  muted: "8A95A8",
  red: "EF4444",
  amber: "F59E0B",
  green: "10B981",
};

function riskColor(score: number): string {
  if (score >= 70) return THEME.red;
  if (score >= 45) return THEME.amber;
  return THEME.green;
}

function typeColor(type: string): string {
  const map: Record<string, string> = {
    api: THEME.accent,
    db: THEME.accentViolet,
    frontend: "10B981",
    service: "6366F1",
  };
  return map[type] ?? THEME.accent;
}

export async function exportSlides(
  analysis: AnalysisGraphData,
  projectName: string
): Promise<Blob> {
  const pptx = new PptxGenJS();

  pptx.defineLayout({ name: "WIDE", width: 13.33, height: 7.5 });
  pptx.layout = "WIDE";

  pptx.theme = { headFontFace: "Arial", bodyFontFace: "Arial" };

  // Helper: dark slide background
  const darkBg = (slide: PptxGenJS.Slide) => {
    slide.background = { fill: THEME.bg };
  };

  // Slide 1: Title
  const titleSlide = pptx.addSlide();
  darkBg(titleSlide);
  titleSlide.addText("PRAXIS", {
    x: 0.5, y: 0.4, w: 12, h: 0.5,
    fontSize: 10, color: THEME.accent, bold: true, charSpacing: 6,
  });
  titleSlide.addText(`${projectName}\nArchitecture Review`, {
    x: 0.5, y: 1.2, w: 12, h: 2,
    fontSize: 40, color: THEME.text, bold: true, breakLine: true,
  });
  titleSlide.addText(`Generated by PRAXIS on ${new Date().toLocaleDateString()}`, {
    x: 0.5, y: 6.8, w: 12, h: 0.4,
    fontSize: 10, color: THEME.muted,
  });

  // Slide 2: Overview
  if (analysis.aiSummary) {
    const overviewSlide = pptx.addSlide();
    darkBg(overviewSlide);
    overviewSlide.addText("System Overview", {
      x: 0.5, y: 0.4, w: 12, h: 0.6,
      fontSize: 24, color: THEME.text, bold: true,
    });
    overviewSlide.addText(analysis.aiSummary, {
      x: 0.5, y: 1.2, w: 12, h: 5.5,
      fontSize: 14, color: THEME.muted, breakLine: true, align: "left", valign: "top",
    });
  }

  // Slide 3: Risk Overview
  const nodes = Object.values(analysis.details);
  if (nodes.length > 0) {
    const riskSlide = pptx.addSlide();
    darkBg(riskSlide);
    riskSlide.addText("Risk Overview", {
      x: 0.5, y: 0.4, w: 12, h: 0.6,
      fontSize: 24, color: THEME.text, bold: true,
    });

    const sorted = [...nodes].sort((a, b) => b.riskScore - a.riskScore);
    sorted.forEach((node, idx) => {
      const row = Math.floor(idx / 3);
      const col = idx % 3;
      const x = 0.5 + col * 4.2;
      const y = 1.2 + row * 1.6;

      riskSlide.addShape(pptx.ShapeType.rect, {
        x, y, w: 4.0, h: 1.4,
        fill: { color: THEME.panel },
        line: { color: typeColor(node.type), width: 1 },
      });
      riskSlide.addText(node.name, {
        x: x + 0.15, y: y + 0.1, w: 3.7, h: 0.4,
        fontSize: 11, color: THEME.text, bold: true,
      });
      riskSlide.addShape(pptx.ShapeType.rect, {
        x: x + 0.15, y: y + 0.6, w: 3.0 * (node.riskScore / 100), h: 0.18,
        fill: { color: riskColor(node.riskScore) },
      });
      riskSlide.addText(`${node.riskScore}/100 risk`, {
        x: x + 0.15, y: y + 0.85, w: 3.7, h: 0.3,
        fontSize: 9, color: THEME.muted,
      });
    });
  }

  // One slide per component
  nodes.forEach((node) => {
    const slide = pptx.addSlide();
    darkBg(slide);

    // Header
    slide.addShape(pptx.ShapeType.rect, {
      x: 0, y: 0, w: 13.33, h: 1.0,
      fill: { color: THEME.panel },
    });
    slide.addText(node.name, {
      x: 0.5, y: 0.15, w: 9, h: 0.6,
      fontSize: 22, color: THEME.text, bold: true,
    });
    slide.addText(node.type.toUpperCase(), {
      x: 10, y: 0.25, w: 3, h: 0.4,
      fontSize: 11, color: typeColor(node.type), bold: true, align: "right",
    });

    // Description
    slide.addText(node.description, {
      x: 0.5, y: 1.2, w: 8, h: 1.4,
      fontSize: 13, color: THEME.muted, breakLine: true, valign: "top",
    });

    // Metrics
    slide.addText("Metrics", { x: 9, y: 1.2, w: 4, h: 0.4, fontSize: 11, color: THEME.accent, bold: true });
    [
      `LOC: ${node.metrics.loc}`,
      `Imports: ${node.metrics.imports}`,
      `Complexity: ${node.metrics.complexity}`,
    ].forEach((metric, i) => {
      slide.addText(metric, { x: 9, y: 1.7 + i * 0.35, w: 4, h: 0.3, fontSize: 11, color: THEME.text });
    });

    // Risk bar
    slide.addText("Risk Score", { x: 0.5, y: 2.8, w: 4, h: 0.3, fontSize: 11, color: THEME.accent, bold: true });
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.5, y: 3.2, w: 7.5, h: 0.25,
      fill: { color: "1E293B" },
    });
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.5, y: 3.2, w: 7.5 * (node.riskScore / 100), h: 0.25,
      fill: { color: riskColor(node.riskScore) },
    });
    slide.addText(`${node.riskScore}/100`, {
      x: 8.2, y: 3.15, w: 1.5, h: 0.35, fontSize: 12, color: riskColor(node.riskScore), bold: true,
    });

    // Dependencies
    if (node.dependencies.length > 0) {
      slide.addText("Dependencies", { x: 0.5, y: 3.7, w: 4, h: 0.3, fontSize: 11, color: THEME.accent, bold: true });
      slide.addText(node.dependencies.join(", "), {
        x: 0.5, y: 4.05, w: 12, h: 0.4, fontSize: 11, color: THEME.muted,
      });
    }

    // AI suggestions
    if (node.remediations?.length) {
      slide.addText("AI Recommendations", {
        x: 0.5, y: 4.6, w: 12, h: 0.4, fontSize: 11, color: THEME.accentViolet, bold: true,
      });
      node.remediations.slice(0, 3).forEach((r, i) => {
        slide.addText(`→ ${r}`, {
          x: 0.5, y: 5.05 + i * 0.45, w: 12, h: 0.4, fontSize: 11, color: THEME.text,
        });
      });
    }
  });

  // Final slide: Top recommendations
  const highRiskNodes = nodes.filter((n) => n.riskScore >= 50).sort((a, b) => b.riskScore - a.riskScore).slice(0, 5);
  if (highRiskNodes.length > 0) {
    const recSlide = pptx.addSlide();
    darkBg(recSlide);
    recSlide.addText("Top Priorities", {
      x: 0.5, y: 0.4, w: 12, h: 0.6, fontSize: 24, color: THEME.text, bold: true,
    });
    highRiskNodes.forEach((node, i) => {
      recSlide.addText(`${i + 1}. ${node.name} (risk: ${node.riskScore}/100)`, {
        x: 0.5, y: 1.2 + i * 0.8, w: 12, h: 0.4,
        fontSize: 14, color: THEME.text, bold: true,
      });
      if (node.remediations?.[0]) {
        recSlide.addText(`   → ${node.remediations[0]}`, {
          x: 0.5, y: 1.55 + i * 0.8, w: 12, h: 0.35,
          fontSize: 12, color: THEME.muted,
        });
      }
    });
    recSlide.addText("Generated by PRAXIS · praxis.app", {
      x: 0.5, y: 7.0, w: 12, h: 0.3, fontSize: 9, color: THEME.muted, align: "center",
    });
  }

  const output = await pptx.write({ outputType: "blob" });
  return output as Blob;
}
